### ISSUE TITLE
No Ticks property defined.

### ISSUE THREAD

**Issue by jmenashe** [supersonicclay/csharp-date#6]
I noticed that your implementation does not include a Ticks property. My guess at your reasoning would be that Ticks are far too precise for an object that represents 24-hour intervals. However, I have found that including Ticks helps with some of my code that expects this property and so I think that this property is still useful to keep around. My implementation is included below.

What are your thoughts on this? Do you have any strong arguments against including this property?

```
public long Ticks
{
	get
	{
		return this._dt.Date.Ticks;
	}
}
```

**Comment by supersonicclay** [comment]
@jmenashe Sorry for delay on this. I totally agree on including this property.
